name: Build macOS dylib

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build dylib
      run: |
        clang -dynamiclib -o msgbox.dylib libs/msgbox/msgbox.c

    - name: Upload dylib artifact
      uses: actions/upload-artifact@v3
      with:
        name: msgbox-dylib
        path: msgbox.dylib
