name: raylib-lucia - Use Prebuilt Shared Libraries

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 0

    steps:
      - name: Download prebuilt libraries
        run: |
          mkdir -p prebuilt
          curl -L -o prebuilt/raylib.dll https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_msvc16.zip
          curl -L -o prebuilt/libraylib.so https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_linux_amd64.tar.gz
          curl -L -o prebuilt/libraylib.dylib https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_macos.tar.gz

      - name: Extract Linux and macOS libraries
        run: |
          tar -xvzf prebuilt/libraylib.so -C prebuilt
          tar -xvzf prebuilt/libraylib.dylib -C prebuilt

      - name: Reorganize into zip/ folder
        run: |
          mkdir -p zip
          cp prebuilt/* zip/

      - name: Create zip file
        run: |
          if [ "$(ls -A zip)" ]; then
            zip -r raylib-shared-libs.zip zip/*
          else
            echo "No files to zip."
          fi

      - name: Upload zip bundle
        uses: actions/upload-artifact@v4
        with:
          name: raylib-shared-libs
          path: raylib-shared-libs.zip
