name: raylib-lucia - Use Prebuilt Shared Libraries

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 0

    steps:
      - name: Download prebuilt libraries
        run: |
          mkdir -p prebuilt
          curl -L -o prebuilt/raylib-win.zip https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_msvc16.zip
          curl -L -o prebuilt/raylib-linux.tar.gz https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_linux_amd64.tar.gz
          curl -L -o prebuilt/raylib-macos.tar.gz https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_macos.tar.gz

      - name: Extract prebuilt libraries
        run: |
            mkdir -p prebuilt/win
            mkdir -p prebuilt/linux
            mkdir -p prebuilt/macos
            unzip prebuilt/raylib-win.zip -d prebuilt/win
            tar -xvzf prebuilt/raylib-linux.tar.gz -C prebuilt/linux
            tar -xvzf prebuilt/raylib-macos.tar.gz -C prebuilt/macos


      - name: Reorganize into zip/ folder
        run: |
          mkdir -p zip
          # Copy actual library files
          cp prebuilt/win/raylib.dll zip/
          cp prebuilt/linux/libraylib.so zip/
          cp prebuilt/macos/libraylib.dylib zip/

      - name: Create zip file
        run: |
          if [ "$(ls -A zip)" ]; then
            zip -j raylib-shared-libs.zip zip/*
          else
            echo "No files to zip."
          fi

      - name: Upload zip bundle
        uses: actions/upload-artifact@v4
        with:
          name: raylib-shared-libs
          path: raylib-shared-libs.zip
