name: raylib-lucia - Use prebuilt shared libs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 0

    steps:
      - name: Download prebuilt libraries
        run: |
          mkdir -p prebuilt
          curl -L -o prebuilt/raylib.dll  https://example.com/raylib/windows/raylib.dll
          curl -L -o prebuilt/libraylib.so https://example.com/raylib/linux/libraylib.so
          curl -L -o prebuilt/libraylib.dylib https://example.com/raylib/macos/libraylib.dylib

      - name: Reorganize into zip/ folder
        run: |
          mkdir -p zip
          cp prebuilt/* zip/

      - name: Create zip file
        run: |
          if [ "$(ls -A zip)" ]; then
            zip -j raylib-shared-libs.zip zip/*
          else
            echo "No files to zip."
          fi

      - name: Upload zip bundle
        uses: actions/upload-artifact@v4
        with:
          name: raylib-shared-libs
          path: raylib-shared-libs.zip
